from __future__ import annotations


def _clean_key(value: str) -> str:
    return " ".join(value.strip().lower().split())


EXERCISE_ALIASES: dict[str, str] = {
    _clean_key("Bench Press (Barbell)"): "Bench Press",
    _clean_key("Bent Over Row (Dumbbell)"): "Bent Over Dumbbell Row",
    _clean_key("Bicep Curl (Barbell)"): "Barbell Bicep Curl",
    _clean_key("Bicep Curl (barbell )"): "Barbell Bicep Curl",
    _clean_key("Bicep Curl (Dumbbell)"): "Dumbbell Bicep Curl",
    _clean_key("Curl Dumbbell"): "Dumbbell Bicep Curl",
    _clean_key("Cable Fly"): "Cable Fly",
    _clean_key("Chin Up"): "Chin-Up",
    _clean_key("Cycling"): "Cycling",
    _clean_key("Deadlift"): "Deadlift",
    _clean_key("Deadlift (Barbell)"): "Deadlift",
    _clean_key("Deadlift - Trap Bar"): "Trap Bar Deadlift",
    _clean_key("Face pull"): "Face Pull",
    _clean_key("Front Raise (Dumbbell)"): "Dumbbell Front Raise",
    _clean_key("Front Squat (Barbell)"): "Front Squat",
    _clean_key("Glute extension."): "Glute Extension",
    _clean_key("Good Morning"): "Good Morning",
    _clean_key("Good Morning (Barbell)"): "Good Morning",
    _clean_key("Hack Squat"): "Hack Squat",
    _clean_key("Hammer Curl"): "Hammer Curl",
    _clean_key("Hammer Curl (Dumbbell )"): "Hammer Curl",
    _clean_key("Hammer Decline Chest Press"): "Hammer Decline Chest Press",
    _clean_key("Hammer High Row - 1 Arm"): "Hammer High Row - One Arm",
    _clean_key("Hammer Row - Wide Grip"): "Hammer Row - Wide Grip",
    _clean_key("Hammer Row Stand 1armed"): "Hammer Row Standing One Arm",
    _clean_key("Hammer back row wide 45 angle"): "Hammer Back Row Wide 45 Degree",
    _clean_key("Hammer lat pulldown"): "Hammer Lat Pulldown",
    _clean_key("Hammer seated row"): "Hammer Seated Row",
    _clean_key("Hammer seated row (CLOSE GRIP)"): "Hammer Seated Row - Close Grip",
    _clean_key("Hammer shoulder press"): "Hammer Shoulder Press",
    _clean_key("Incline Bench Press"): "Incline Bench Press",
    _clean_key("Incline Bench Press (Barbell)"): "Incline Bench Press",
    _clean_key("Incline Press (Dumbbell)"): "Incline Dumbbell Press",
    _clean_key("Landmine Press"): "Landmine Press",
    _clean_key("Lat Pulldown"): "Lat Pulldown",
    _clean_key("Lat Pulldown "): "Lat Pulldown",
    _clean_key("Lat Pulldown (Cable)"): "Lat Pulldown",
    _clean_key("Lat Pulldown Closegrip"): "Lat Pulldown - Close Grip",
    _clean_key("Lateral Raise"): "Dumbbell Lateral Raise",
    _clean_key("Lateral Raise (Dumbbell)"): "Dumbbell Lateral Raise",
    _clean_key("Lateral Raise (Dumbbells)"): "Dumbbell Lateral Raise",
    _clean_key("Leg Extension (Machine)"): "Leg Extension",
    _clean_key("Leg curl"): "Leg Curl",
    _clean_key("Leg outward fly"): "Hip Abductor Machine",
    _clean_key("Leg press"): "Leg Press",
    _clean_key("Leg press (hinge )"): "Leg Press",
    _clean_key("Low Incline Dumbbell Bench"): "Low Incline Dumbbell Press",
    _clean_key("Military Press (Standing)"): "Standing Barbell Overhead Press",
    _clean_key("Neutral Chin"): "Neutral Grip Chin-Up",
    _clean_key("Overhead Press (Barbell)"): "Standing Barbell Overhead Press",
    _clean_key("Overhead Press (Dumbbell)"): "Standing Dumbbell Overhead Press",
    _clean_key("Pull Up"): "Pull-Up",
    _clean_key("Rack Pull - 1 Pin"): "Rack Pull - 1 Pin",
    _clean_key("Rack Pull 2 Pin"): "Rack Pull - 2 Pin",
    _clean_key("Rear delt fly"): "Rear Delt Fly",
    _clean_key("Romanian Deadlift (Barbell)"): "Romanian Deadlift",
    _clean_key("Rope Never Ending"): "Battle Ropes",
    _clean_key("Rotator cuff work."): "Rotator Cuff Work",
    _clean_key("Seated Cable Row (close Grip)"): "Seated Cable Row - Close Grip",
    _clean_key("Seated Military Press"): "Seated Barbell Shoulder Press",
    _clean_key("Seated Military Press (Dumbbell)"): "Seated Dumbbell Shoulder Press",
    _clean_key("Seated Row"): "Seated Row",
    _clean_key("Seated Shoulder  Press (Barbell)"): "Seated Barbell Shoulder Press",
    _clean_key("Seated Shoulder Press (Dumbbell)"): "Seated Dumbbell Shoulder Press",
    _clean_key("Shoulder Press (Standing)"): "Standing Barbell Overhead Press",
    _clean_key("Shrugs"): "Shrugs",
    _clean_key("Shrugs (dumbbell)"): "Dumbbell Shrugs",
    _clean_key("Skullcrusher (Barbell)"): "Skullcrusher",
    _clean_key("Sling Shot Bench"): "Sling Shot Bench Press",
    _clean_key("Sling Shot Incline"): "Sling Shot Incline Press",
    _clean_key("Squat"): "Back Squat",
    _clean_key("Squat (Barbell)"): "Back Squat",
    _clean_key("Stairmaster"): "Stairmaster",
    _clean_key("T-bar Row"): "T-Bar Row",
    _clean_key("Tricep Extension"): "Tricep Extension",
    _clean_key("Tricep pushdown"): "Tricep Pushdown",
    _clean_key("Weighted dips"): "Weighted Dips",
    _clean_key("close grip Bench"): "Close Grip Bench Press",
    _clean_key("curl ez bar"): "EZ Bar Curl",
    _clean_key("high bar squat"): "High Bar Squat",
    _clean_key("kettlebell Swings"): "Kettlebell Swing",
    _clean_key("lying Skullcrusher"): "Skullcrusher",
    _clean_key("sumo deadlift"): "Sumo Deadlift",
}


def normalize_exercise_name(raw_name: str) -> str:
    cleaned = _clean_key(raw_name)
    return EXERCISE_ALIASES.get(cleaned, " ".join(raw_name.strip().split()))


EXERCISE_OPTIONS = sorted(set(EXERCISE_ALIASES.values()))

MUSCLE_GROUPS: dict[str, str] = {
    "Back Squat": "Picioare",
    "Barbell Bicep Curl": "Biceps",
    "Battle Ropes": "Conditionare",
    "Bench Press": "Piept",
    "Bent Over Dumbbell Row": "Spate",
    "Cable Fly": "Piept",
    "Chin-Up": "Spate",
    "Close Grip Bench Press": "Triceps",
    "Cycling": "Conditionare",
    "Deadlift": "Spate",
    "Dumbbell Bicep Curl": "Biceps",
    "Dumbbell Front Raise": "Umeri",
    "Dumbbell Lateral Raise": "Umeri",
    "Dumbbell Shrugs": "Trap",
    "EZ Bar Curl": "Biceps",
    "Face Pull": "Umeri",
    "Front Squat": "Picioare",
    "Glute Extension": "Picioare",
    "Good Morning": "Picioare",
    "Hack Squat": "Picioare",
    "Hammer Back Row Wide 45 Degree": "Spate",
    "Hammer Curl": "Biceps",
    "Hammer Decline Chest Press": "Piept",
    "Hammer High Row - One Arm": "Spate",
    "Hammer Lat Pulldown": "Spate",
    "Hammer Row - Wide Grip": "Spate",
    "Hammer Row Standing One Arm": "Spate",
    "Hammer Seated Row": "Spate",
    "Hammer Seated Row - Close Grip": "Spate",
    "Hammer Shoulder Press": "Umeri",
    "High Bar Squat": "Picioare",
    "Hip Abductor Machine": "Picioare",
    "Incline Bench Press": "Piept",
    "Incline Dumbbell Press": "Piept",
    "Kettlebell Swing": "Posterior Chain",
    "Landmine Press": "Umeri",
    "Lat Pulldown": "Spate",
    "Lat Pulldown - Close Grip": "Spate",
    "Leg Curl": "Picioare",
    "Leg Extension": "Picioare",
    "Leg Press": "Picioare",
    "Low Incline Dumbbell Press": "Piept",
    "Neutral Grip Chin-Up": "Spate",
    "Pull-Up": "Spate",
    "Rack Pull - 1 Pin": "Spate",
    "Rack Pull - 2 Pin": "Spate",
    "Rear Delt Fly": "Umeri",
    "Romanian Deadlift": "Picioare",
    "Rotator Cuff Work": "Umeri",
    "Seated Barbell Shoulder Press": "Umeri",
    "Seated Cable Row - Close Grip": "Spate",
    "Seated Dumbbell Shoulder Press": "Umeri",
    "Seated Row": "Spate",
    "Shrugs": "Trap",
    "Skullcrusher": "Triceps",
    "Sling Shot Bench Press": "Piept",
    "Sling Shot Incline Press": "Piept",
    "Stairmaster": "Conditionare",
    "Standing Barbell Overhead Press": "Umeri",
    "Standing Dumbbell Overhead Press": "Umeri",
    "Sumo Deadlift": "Picioare",
    "T-Bar Row": "Spate",
    "Trap Bar Deadlift": "Picioare",
    "Tricep Extension": "Triceps",
    "Tricep Pushdown": "Triceps",
    "Weighted Dips": "Piept",
}

EXERCISE_CATEGORY: dict[str, str] = {
    "Back Squat": "Legs",
    "Barbell Bicep Curl": "Pull",
    "Battle Ropes": "Conditioning",
    "Bench Press": "Push",
    "Bent Over Dumbbell Row": "Pull",
    "Cable Fly": "Push",
    "Chin-Up": "Pull",
    "Close Grip Bench Press": "Push",
    "Cycling": "Conditioning",
    "Deadlift": "Pull",
    "Dumbbell Bicep Curl": "Pull",
    "Dumbbell Front Raise": "Push",
    "Dumbbell Lateral Raise": "Push",
    "Dumbbell Shrugs": "Pull",
    "EZ Bar Curl": "Pull",
    "Face Pull": "Pull",
    "Front Squat": "Legs",
    "Glute Extension": "Legs",
    "Good Morning": "Legs",
    "Hack Squat": "Legs",
    "Hammer Back Row Wide 45 Degree": "Pull",
    "Hammer Curl": "Pull",
    "Hammer Decline Chest Press": "Push",
    "Hammer High Row - One Arm": "Pull",
    "Hammer Lat Pulldown": "Pull",
    "Hammer Row - Wide Grip": "Pull",
    "Hammer Row Standing One Arm": "Pull",
    "Hammer Seated Row": "Pull",
    "Hammer Seated Row - Close Grip": "Pull",
    "Hammer Shoulder Press": "Push",
    "High Bar Squat": "Legs",
    "Hip Abductor Machine": "Legs",
    "Incline Bench Press": "Push",
    "Incline Dumbbell Press": "Push",
    "Kettlebell Swing": "Legs",
    "Landmine Press": "Push",
    "Lat Pulldown": "Pull",
    "Lat Pulldown - Close Grip": "Pull",
    "Leg Curl": "Legs",
    "Leg Extension": "Legs",
    "Leg Press": "Legs",
    "Low Incline Dumbbell Press": "Push",
    "Neutral Grip Chin-Up": "Pull",
    "Pull-Up": "Pull",
    "Rack Pull - 1 Pin": "Pull",
    "Rack Pull - 2 Pin": "Pull",
    "Rear Delt Fly": "Pull",
    "Romanian Deadlift": "Legs",
    "Rotator Cuff Work": "Push",
    "Seated Barbell Shoulder Press": "Push",
    "Seated Cable Row - Close Grip": "Pull",
    "Seated Dumbbell Shoulder Press": "Push",
    "Seated Row": "Pull",
    "Shrugs": "Pull",
    "Skullcrusher": "Push",
    "Sling Shot Bench Press": "Push",
    "Sling Shot Incline Press": "Push",
    "Stairmaster": "Conditioning",
    "Standing Barbell Overhead Press": "Push",
    "Standing Dumbbell Overhead Press": "Push",
    "Sumo Deadlift": "Legs",
    "T-Bar Row": "Pull",
    "Trap Bar Deadlift": "Legs",
    "Tricep Extension": "Push",
    "Tricep Pushdown": "Push",
    "Weighted Dips": "Push",
}
